# CADENA DE MARKOV

Se asume que tenemos un puesto de restaurante donde solo servimos tres tipos de comida que son <br> 
hamburguesa, pizza y hot dog, pero tienen un patron especifico, solo sirven uno de estas tres comidas por dia y <br>
depende de lo que hayan servido el dia anterior, en terminos generales se busca la manera de predecir lo que <br>
serviran mañana si sabemos lo que sirvieron hoy y las ganancias estimadas a obtener. <br>
Por ejemplo, hay una probabilidad de 60% de que mañana sea un dia de pizza dado que hoy es una <br> 
hamburguesa, hay una probabilidad de 20% de que mañana vuelvan a servir hamburguesas y la probabilidad <br>
restante es para transitar a hot dog. <br>
En el caso de la pizza es practicamente nulo que se repita, pero puede pasar al menu del dia en un 30% para <br>
hamburguesa y un 70% para hot dog. <br>
El hot dog es de los productos mas vendidos y se puede repetir en un 50%, por reglas del negocio no puede <br>
pasar a ventas de pizza, pero si puede transitar en el porcentaje restante al menu de hamburguesas.

Se desea determinar <br>
- El restaurante sirvio pizza el primer dia y hamburguesa el segundo, nuevamente pizza el tercer dia, ¿Cual <br> 
es la probabilidad de que sirvan hot dogs el cuarto dia?

- Las estadisticas de inicio indican que se vendieron el primer dia 30 hamburguesas, 10 pizzas y 40 hot dogs. <br>
la ganancia estimada por cada tipo de alimento es de 40 pesos, 50 pesos y 25 pesos respectivamente, <br>
¿Cual sera la utilidad mensual(30 dias) esperada de ganancias para el negocio acorde a la cadena de markov?

In [180]:
""""
    H    P    HD
H [0.2, 0.6, 0.2]
P [0.3, 0, 0.7]
HD [0.5, 0, 0.5]
"""
#¿CUALES SON LOS PORCENTAJES DE MERCADO EN EL ESTADO ESTABLE PARA LAS DOS CERVECERIAS MAS GRANDES?

import numpy as np
m1 = np.matrix([[0.2, 0.6, 0.2],[0.3, 0, 0.7], [0.5, 0, 0.5]])
m1

matrix([[0.2, 0.6, 0.2],
        [0.3, 0. , 0.7],
        [0.5, 0. , 0.5]])

In [181]:
m_aux = np.matrix([[], [], []])
m_aux_anterior = np.matrix([[], [], []])

In [182]:
#DETECTAR MATRIZ ESTABLE
for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1-------------", i + 1)
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print(y, "-------", i + 1)
print()
print("La matriz estable es:\n", np.round(m_aux, 4))
print("-------------------")
print(np.round(m_aux, 3))

[[0.32 0.12 0.56]
 [0.41 0.18 0.41]
 [0.35 0.3  0.35]]
1------------- 1
[[0.38  0.192 0.428]
 [0.341 0.246 0.413]
 [0.335 0.21  0.455]]
2 ------- 2
[[0.3476 0.228  0.4244]
 [0.3485 0.2046 0.4469]
 [0.3575 0.201  0.4415]]
3 ------- 3
[[0.35012 0.20856 0.44132]
 [0.35453 0.2091  0.43637]
 [0.35255 0.2145  0.43295]]
4 ------- 4
[[0.353252 0.210072 0.436676]
 [0.351821 0.212718 0.435461]
 [0.351335 0.21153  0.437135]]
5 ------- 5
[[0.35201   0.2119512 0.4360388]
 [0.3519101 0.2110926 0.4369973]
 [0.3522935 0.210801  0.4369055]]
6 ------- 6
[[0.35200676 0.211206   0.43678724]
 [0.35220845 0.21114606 0.43664549]
 [0.35215175 0.2113761  0.43647215]]
7 ------- 7
[[0.35215677 0.21120406 0.43663917]
 [0.35210825 0.21132507 0.43656668]
 [0.35207925 0.21129105 0.43662969]]
8 ------- 8
[[0.35211216 0.21129406 0.43659378]
 [0.35210251 0.21126495 0.43663254]
 [0.35211801 0.21124755 0.43663443]]
9 ------- 9
[[0.35210754 0.21126729 0.43662517]
 [0.35211626 0.21126151 0.43662224]
 [0.35211509 0.21127081

In [183]:
x_dia3 = np.array([0, 1, 0])

# Probabilidades para el día 4
x_dia4 = x_dia3 * m1

print("Probabilidades para el día 4:", x_dia4)


Probabilidades para el día 4: [[0.3 0.  0.7]]


In [184]:
alimentos = np.matrix([[30, 10, 40]])

precios = np.matrix([[40], [50], [25]])

util_dia = alimentos @ precios

print("Utilidad del día:", util_dia[0, 0])

util_mensual = util_dia * 30
print("Utilidad mensual:", util_mensual[0, 0])

Utilidad del día: 2700
Utilidad mensual: 81000


# LINEAS DE ESPERA (COLAS)

In [185]:
from math import factorial

In [186]:
#UtilizacionPromedio
def p(tasaLlegada, tasaServicio, servidores):
    return (float(tasaLlegada/(tasaServicio*servidores)))

In [187]:
#p0
def pZero(tasaLlegada, tasaServicio, servidores):
    calc_parte1 = 0
    for x in range(servidores):
        calc_parte1 += ((tasaLlegada/tasaServicio)**x)/factorial(x)
    seccion1 = ((tasaLlegada/tasaServicio)**servidores/factorial(servidores))
    seccion2 = 1/(1-p(tasaLlegada, tasaServicio, servidores))
    result_seccion2 = seccion1 * seccion2
    return 1/ (calc_parte1 + result_seccion2)

In [188]:
#CANTIDAD PROMEDIO DE PACIENTES EN COLA (LQ)
def lq(tasaServicio, tasaLlegada, servidores):
    num = pZero(tasaLlegada, tasaServicio, servidores) * ((tasaLlegada/tasaServicio)**servidores) * p(tasaLlegada, tasaServicio, servidores)
    den = factorial(servidores) * ((1-p(tasaLlegada, tasaServicio, servidores))**2)

    return num/den

In [189]:
#CANTIDAD PROMEDIO DE PACIENTES EN EL SISTEMA
def l(tasaServicio, tasaLlegada, servidores):
    return lq(tasaServicio, tasaLlegada, servidores) + (tasaLlegada/tasaServicio)

In [190]:
#TIEMPO PROMEDIO EN COLA
def wq(tasaServicio, tasaLlegada, servidores):
    return lq(tasaServicio, tasaLlegada, servidores) / tasaLlegada  

In [191]:
def w(tasaServicio, tasaLlegada, servidores):
    return wq(tasaServicio, tasaLlegada, servidores) + (1/tasaServicio)

In [192]:
tasaLlegada = 12
tasaServicio = 9
servidores = 3

In [193]:
#¿Cantidad promedio de pacientes en cola?
print("Cantidad promedio de pacientes en cola: ", lq(tasaServicio, tasaLlegada, servidores))

#¿Cantidad promedio de pacientes en el sistema?
print("Cantidad promedio de pacientes en el sistema: ", l(tasaServicio, tasaLlegada, servidores))

#¿Tiempo promedio en cola?
print("Tiempo promedio en cola: ", wq(tasaServicio, tasaLlegada, servidores))

#¿Tiempo promedio en el sistema?
print("Tiempo promedio de permanencia en el sistema: ", w(tasaServicio, tasaLlegada, servidores))

Cantidad promedio de pacientes en cola:  0.14463276836158187
Cantidad promedio de pacientes en el sistema:  1.477966101694915
Tiempo promedio en cola:  0.01205273069679849
Tiempo promedio de permanencia en el sistema:  0.1231638418079096


In [194]:
# ¿Contrataria a no a un cuarto medico, por que si o por que no?

tasaLlegada = 12
tasaServicio = 9
servidores = 4

In [195]:
#¿Cantidad promedio de pacientes en cola?
print("Cantidad promedio de pacientes en cola: ", lq(tasaServicio, tasaLlegada, servidores))

#¿Cantidad promedio de pacientes en el sistema?
print("Cantidad promedio de pacientes en el sistema: ", l(tasaServicio, tasaLlegada, servidores))

#¿Tiempo promedio en cola?
print("Tiempo promedio en cola: ", wq(tasaServicio, tasaLlegada, servidores))

#¿Tiempo promedio en el sistema?
print("Tiempo promedio de permanencia en el sistema: ", w(tasaServicio, tasaLlegada, servidores))

Cantidad promedio de pacientes en cola:  0.025889967637540447
Cantidad promedio de pacientes en el sistema:  1.3592233009708736
Tiempo promedio en cola:  0.0021574973031283705
Tiempo promedio de permanencia en el sistema:  0.11326860841423947


No se recomendaría contratar un cuarto médico, porque el sistema actual con 3 médicos ya opera de manera eficiente.