In [66]:
import numpy as np

In [67]:
m1 = np.matrix([[0.80, 0.15, 0.05],[0.3, 0.6, 0.1], [0.4, 0.3, 0.3]])
m1

matrix([[0.8 , 0.15, 0.05],
        [0.3 , 0.6 , 0.1 ],
        [0.4 , 0.3 , 0.3 ]])

In [68]:
#FUNCIONANDO, CUAL ES LA PROBABILIDAD DE QUE AL DIA SIGUIENTE ESTE EN MANTENIMIENTO
#F, M. A
v3 = np.matrix([[1, 0, 0]])
v3_result = np.dot(v3, m1)

print("Cual es la probabilidad de que si hoy esta funcionando, mañana pase a mantenimiento", v3_result[0,1] * 100)

Cual es la probabilidad de que si hoy esta funcionando, mañana pase a mantenimiento 15.0


In [69]:
# Probabilidad a dos dias de estar en funcionamiento a averiado

p2 = np.dot(m1, m1)

v4 = np.matrix([[1, 0, 0]])
v4_result = np.dot(v4, p2)

print("Cual es la probabilidad de que si hoy esta funcionando, mañana pase a averiada", round(v4_result[0,2] * 100, 0))

Cual es la probabilidad de que si hoy esta funcionando, mañana pase a averiada 7.0


In [70]:
#DETECTAR MATRIZ ESTABLE
for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1-------------", i + 1)
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print(y, "-------", i + 1)
print()
print("La matriz estable es:\n", np.round(m_aux, 4))
print("-------------------")
print(np.round(m_aux, 4))

[[0.705 0.225 0.07 ]
 [0.46  0.435 0.105]
 [0.53  0.33  0.14 ]]
1------------- 1
[[0.6595  0.26175 0.07875]
 [0.5405  0.3615  0.098  ]
 [0.579   0.3195  0.1015 ]]
2 ------- 2
[[0.637625 0.2796   0.082775]
 [0.58005  0.327375 0.092575]
 [0.59965  0.309    0.09135 ]]
3 ------- 3
[[0.62709    0.28823625 0.08467375]
 [0.5992825  0.311205   0.0895125 ]
 [0.60896    0.3027525  0.0882875 ]]
4 ------- 4
[[0.62201238 0.29240738 0.08558025]
 [0.6085925  0.30346912 0.08793837]
 [0.61330875 0.29948175 0.0872095 ]]
5 ------- 5
[[0.61956421 0.29442036 0.08601543]
 [0.61309009 0.29975186 0.08715805]
 [0.61537533 0.29784821 0.08677646]]
6 ------- 6
[[0.61838365 0.29539148 0.08622488]
 [0.61526085 0.29796205 0.08677711]
 [0.61636531 0.29704816 0.08658653]]
7 ------- 7
[[0.61781431 0.2958599  0.08632579]
 [0.61630813 0.29709949 0.08659238]
 [0.61684131 0.29665965 0.08649904]]
8 ------- 8
[[0.61753974 0.29608582 0.08637444]
 [0.61681331 0.29668363 0.08650307]
 [0.61707056 0.2964717  0.08645774]]
9 ------

In [ ]:
vector_estable = np.round(m_aux[0],4)

#CONVERTIRLO A PORCENTAJE
porcentaje = vector_estable * 100
print("Distribucion estable estacionaria en %")
print(f"Funcionando:{porcentaje[0,0]:.2f}%")
print(f"Mantenimiento:{porcentaje[0,1]:.2f}%")
print(f"Averiada:{porcentaje[0,2]:.2f}%")

Distribucion estable estacionaria en %
funcionando:61.73%
funcionando:29.63%
funcionando:8.64%
