LA CERVECERIA MAS IMPORTANTE DEL MUNDO (GUINESS) HA CONTRATADO UN ANALISTA DE INVESTIGACION DE OPERACIONES PARA ANALIZAR SU POSICION EN EL MERCADO. ESTAN PREOCUPADOS EN ESPECIAL POR SU MAYOR COMPETIDOR (HEINEKEN). EL ANALISTA PIENSA QUE EL CAMBIO DE MARCA SE PUEDE MODELAR CON UNA CADENA DE MARKOV INCLUYENDO 3 ESTADOS, LOS ESTADOS G Y H REPRESENTAN A LOS CLIENTES QUE BEBEN CERVEZA PRODUCIDA POR LAS MENCIONADAS CERVECERIAS Y EN EL ESTADO I REPRESENTA A TODAS LAS DEMAS MARCAS. LOS DATOS SE TOMAN CADA MES Y EL ANALISTA A CONSTRUIDO LA SIGUIENTE MATRIZ DE TRANSICION DE DATOS HISTORICOS.

In [ ]:
""""
   G    H     I
G[0.7, 0.2, 0.1]
H[0.2, 0.75, 0.05]
I[0.1, 0.1, 0.8]
"""
#¿CUALES SON LOS PORCENTAJES DE MERCADO EN EL ESTADO ESTABLE PARA LAS DOS CERVECERIAS MAS GRANDES?

import numpy as np
m1 = np.matrix([[0.7, 0.2, 0.1],[0.2, 0.75, 0.05], [0.1, 0.1, 0.8]])
m1

matrix([[0.7 , 0.2 , 0.1 ],
        [0.2 , 0.75, 0.05],
        [0.1 , 0.1 , 0.8 ]])

In [29]:
m_aux = np.matrix([[], [], []])
m_aux_anterior = np.matrix([[], [], []])

In [30]:
#DETECTAR MATRIZ ESTABLE
for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1-------------", i + 1)
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print(y, "-------", i + 1)
print()
print("La matriz estable es:\n", np.round(m_aux, 4))
print("-------------------")
print(np.round(m_aux, 3))

[[0.54   0.3    0.16  ]
 [0.295  0.6075 0.0975]
 [0.17   0.175  0.655 ]]
1------------- 1
[[0.454    0.349    0.197   ]
 [0.33775  0.524375 0.137875]
 [0.2195   0.23075  0.54975 ]]
2 ------- 2
[[0.4073     0.37225    0.22045   ]
 [0.3550875  0.47461875 0.17029375]
 [0.254775   0.2719375  0.4732875 ]]
3 ------- 3
[[0.381605   0.3826925  0.2357025 ]
 [0.36051437 0.44401094 0.19547469]
 [0.28005875 0.30223688 0.41770438]]
4 ------- 4
[[0.36723225 0.38691062 0.24585713]
 [0.36070972 0.42465855 0.21463173]
 [0.29825894 0.32445984 0.37728122]]
5 ------- 5
[[0.35903041 0.38821513 0.25275446]
 [0.35889169 0.41209903 0.22900929]
 [0.31140135 0.34072479 0.34787386]]
6 ------- 6
[[0.35423976 0.38824288 0.25751736]
 [0.35654491 0.40375354 0.23970155]
 [0.32091329 0.35261125 0.32647546]]
7 ------- 7
[[0.35136814 0.38778185 0.26085001]
 [0.3543023  0.39809429 0.24760341]
 [0.3278091  0.36128864 0.31090226]]
8 ------- 8
[[0.34959907 0.38719501 0.26320591]
 [0.35239081 0.39419152 0.25341767]
 [0.33281

In [31]:
print("El porcentaje para guinness en el mercado es:", round(m_aux[2,0] * 100, 2), "%")

print("El porcentaje para heineken en el mercado es:", round(m_aux[2,1] * 100, 2), "%")

print("El porcentaje para las demas en el mercado es:", round(m_aux[2,2] * 100, 2), "%")

El porcentaje para guinness en el mercado es: 34.62 %
El porcentaje para heineken en el mercado es: 38.46 %
El porcentaje para las demas en el mercado es: 26.92 %


In [32]:
#DETERMINAR VALOR DE LA POBLACION
poblacion_inicial = np.matrix([6000,3000,1000])
poblacion_inicial

matrix([[6000, 3000, 1000]])

In [33]:
print("Poblacion inicial----V0")
for z in range(50):
    if z == 0:
        poblacion_inicial = np.dot(poblacion_inicial, m1)
        poblacion_inicial = np.round(poblacion_inicial, 2)
        print("Poblacion inicial")
        print("-------------", z+1)
    else:
        poblacion_anterior = poblacion_inicial
        poblacion_inicial = np.dot(poblacion_inicial, m1)
        poblacion_inicial = np.round(poblacion_inicial, 2)
        if (np.array_equal(poblacion_inicial, poblacion_anterior)):
            print("Poblacion inicial y anterior iguales")
            print("*** numero de iteraciones", str(z), "***")
            poblacion_inicial = np.round(poblacion_inicial, 0)
            poblacion_inicial = poblacion_inicial.astype(int)
            print("Poblacion final:\n", poblacion_inicial)
            print("N ---------", z+1)
            break
print(poblacion_inicial)
print("La poblacion se estabiliza en la iteracion", z+1)

Poblacion inicial----V0
Poblacion inicial
------------- 1
Poblacion inicial y anterior iguales
*** numero de iteraciones 35 ***
Poblacion final:
 [[3462 3846 2692]]
N --------- 36
[[3462 3846 2692]]
La poblacion se estabiliza en la iteracion 36
