Ejemplo de Matriz 2x2, determinar la estable

In [11]:
import numpy as np
m1 = np.matrix([[0.8, 0.2],[0.3, 0.7]])
m1

matrix([[0.8, 0.2],
        [0.3, 0.7]])

In [12]:
m_aux = np.matrix([[], []])
m_aux_anterior = np.matrix([[], []])

In [13]:
#DETECTAR MATRIZ ESTABLE
for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1-------------", i + 1)
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print(y, "-------", i + 1)
print()
print("La matriz estable es:\n", np.round(m_aux, 4))

[[0.7  0.3 ]
 [0.45 0.55]]
1------------- 1
[[0.65  0.35 ]
 [0.525 0.475]]
2 ------- 2
[[0.625  0.375 ]
 [0.5625 0.4375]]
3 ------- 3
[[0.6125  0.3875 ]
 [0.58125 0.41875]]
4 ------- 4
[[0.60625  0.39375 ]
 [0.590625 0.409375]]
5 ------- 5
[[0.603125  0.396875 ]
 [0.5953125 0.4046875]]
6 ------- 6
[[0.6015625  0.3984375 ]
 [0.59765625 0.40234375]]
7 ------- 7
[[0.60078125 0.39921875]
 [0.59882812 0.40117187]]
8 ------- 8
[[0.60039063 0.39960938]
 [0.59941406 0.40058594]]
9 ------- 9
[[0.60019531 0.39980469]
 [0.59970703 0.40029297]]
10 ------- 10
[[0.60009766 0.39990234]
 [0.59985352 0.40014648]]
11 ------- 11
[[0.60004883 0.39995117]
 [0.59992676 0.40007324]]
12 ------- 12
[[0.60002441 0.39997559]
 [0.59996338 0.40003662]]
13 ------- 13
[[0.60001221 0.39998779]
 [0.59998169 0.40001831]]
14 ------- 14
[[0.6000061  0.3999939 ]
 [0.59999084 0.40000916]]
15 ------- 15
[[0.60000305 0.39999695]
 [0.59999542 0.40000458]]
16 ------- 16
[[0.60000153 0.39999847]
 [0.59999771 0.40000229]]
17 ---