# Cadenas de Markov

1.- (Cadena de MARKOV) El departamento de estudios de mercado de una fábrica estima que el 20% de la gente que compra un producto un mes, no lo comprará el mes siguiente.

Además, el 30% de quienes no lo compren un mes lo adquirirá al mes siguiente.

En una población de 1000 individuos, 100 compraron el producto el primer mes. ¿Cuántos lo comprarán al mes próximo? ¿Y dentro de dos meses?

In [125]:
""" 
    NC  SC
NC  0.7 0.3
SC  0.2 0.8
"""
import numpy as np
m1 = np.matrix([[0.7, 0.3], [0.2, 0.8]])
m1

matrix([[0.7, 0.3],
        [0.2, 0.8]])

In [126]:
m_aux = np.matrix([[], []])
m_aux_anterior = np.matrix([[], []])

In [127]:
#DETECTAR MATRIZ ESTABLE
for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1-------------", i + 1)
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print(y, "-------", i + 1)
print()
print("La matriz estable es:\n", np.round(m_aux, 4))

[[0.55 0.45]
 [0.3  0.7 ]]
1------------- 1
[[0.475 0.525]
 [0.35  0.65 ]]
2 ------- 2
[[0.4375 0.5625]
 [0.375  0.625 ]]
3 ------- 3
[[0.41875 0.58125]
 [0.3875  0.6125 ]]
4 ------- 4
[[0.409375 0.590625]
 [0.39375  0.60625 ]]
5 ------- 5
[[0.4046875 0.5953125]
 [0.396875  0.603125 ]]
6 ------- 6
[[0.40234375 0.59765625]
 [0.3984375  0.6015625 ]]
7 ------- 7
[[0.40117188 0.59882813]
 [0.39921875 0.60078125]]
8 ------- 8
[[0.40058594 0.59941406]
 [0.39960938 0.60039063]]
9 ------- 9
[[0.40029297 0.59970703]
 [0.39980469 0.60019531]]
10 ------- 10
[[0.40014648 0.59985352]
 [0.39990234 0.60009766]]
11 ------- 11
[[0.40007324 0.59992676]
 [0.39995117 0.60004883]]
12 ------- 12
[[0.40003662 0.59996338]
 [0.39997559 0.60002441]]
13 ------- 13
[[0.40001831 0.59998169]
 [0.39998779 0.60001221]]
14 ------- 14
[[0.40000916 0.59999084]
 [0.3999939  0.6000061 ]]
15 ------- 15
[[0.40000458 0.59999542]
 [0.39999695 0.60000305]]
16 ------- 16
[[0.40000229 0.59999771]
 [0.39999847 0.60000153]]
17 ---

In [128]:

poblacion_inicial = np.matrix([900, 100])
poblacion_inicial

matrix([[900, 100]])

In [129]:
#¿Cuantos lo comprararn el mes proximo?
poblacion_proxima = np.dot(poblacion_inicial, m1)
print("La poblacion del proximo mes es:\n", np.round(poblacion_proxima, 4))

La poblacion del proximo mes es:
 [[650. 350.]]


In [130]:
#¿Cuantos lo comprararn en 2 meses?
poblacion_dos = np.dot(poblacion_proxima, m1)
print("La poblacion del proximo mes es:\n", np.round(poblacion_dos, 4))

La poblacion del proximo mes es:
 [[525. 475.]]


2.- (Cadena de MARKOV) La cervecería más importante del mundo (Guiness) ha contratado a un analista de investigación de operaciones para analizar su posición en el mercado. Están preocupados en especial por su mayor competidor (Heineken). El analista piensa que el cambio de marca se puede modelar como una cadena de Markov incluyendo tres estados, los estados G y H representan a los clientes que beben cerveza producida por las mencionadas cervecerías y el estado I representa todas las demás marcas. Los datos se

toman cada mes y el analista ha construido la siguiente matriz de transición de los datos históricos.

In [131]:
""""
   G    H     I
G[0.7, 0.2, 0.1]
H[0.2, 0.75, 0.05]
I[0.1, 0.1, 0.8]
"""
#¿CUALES SON LOS PORCENTAJES DE MERCADO EN EL ESTADO ESTABLE PARA LAS DOS CERVECERIAS MAS GRANDES?

import numpy as np
m1 = np.matrix([[0.7, 0.2, 0.1],[0.2, 0.75, 0.05], [0.1, 0.1, 0.8]])
m1

matrix([[0.7 , 0.2 , 0.1 ],
        [0.2 , 0.75, 0.05],
        [0.1 , 0.1 , 0.8 ]])

In [132]:
m_aux = np.matrix([[], [], []])
m_aux_anterior = np.matrix([[], [], []])

In [133]:
#DETECTAR MATRIZ ESTABLE
for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)
        print(m_aux)
        print("1-------------", i + 1)
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        if (np.array_equal(m_aux, m_aux_anterior)):
            break
        print(y, "-------", i + 1)
print()
print("La matriz estable es:\n", np.round(m_aux, 4))
print("-------------------")
print(np.round(m_aux, 3))

[[0.54   0.3    0.16  ]
 [0.295  0.6075 0.0975]
 [0.17   0.175  0.655 ]]
1------------- 1
[[0.454    0.349    0.197   ]
 [0.33775  0.524375 0.137875]
 [0.2195   0.23075  0.54975 ]]
2 ------- 2
[[0.4073     0.37225    0.22045   ]
 [0.3550875  0.47461875 0.17029375]
 [0.254775   0.2719375  0.4732875 ]]
3 ------- 3
[[0.381605   0.3826925  0.2357025 ]
 [0.36051437 0.44401094 0.19547469]
 [0.28005875 0.30223688 0.41770438]]
4 ------- 4
[[0.36723225 0.38691062 0.24585713]
 [0.36070972 0.42465855 0.21463173]
 [0.29825894 0.32445984 0.37728122]]
5 ------- 5
[[0.35903041 0.38821513 0.25275446]
 [0.35889169 0.41209903 0.22900929]
 [0.31140135 0.34072479 0.34787386]]
6 ------- 6
[[0.35423976 0.38824288 0.25751736]
 [0.35654491 0.40375354 0.23970155]
 [0.32091329 0.35261125 0.32647546]]
7 ------- 7
[[0.35136814 0.38778185 0.26085001]
 [0.3543023  0.39809429 0.24760341]
 [0.3278091  0.36128864 0.31090226]]
8 ------- 8
[[0.34959907 0.38719501 0.26320591]
 [0.35239081 0.39419152 0.25341767]
 [0.33281

In [134]:
print("El porcentaje para guinness en el mercado es:", round(m_aux[2,0] * 100, 2), "%")

print("El porcentaje para heineken en el mercado es:", round(m_aux[2,1] * 100, 2), "%")

print("El porcentaje para las demas en el mercado es:", round(m_aux[2,2] * 100, 2), "%")

El porcentaje para guinness en el mercado es: 34.62 %
El porcentaje para heineken en el mercado es: 38.46 %
El porcentaje para las demas en el mercado es: 26.92 %


3.- Problema Planteado - Teoria de colas

Una empresa tiene un centro de servicio donde los clientes llegan en promedio 8 clientes por hora (λ\lambda) siguiendo un proceso de distribución de Poisson. Para atender a los clientes, hay tres servidores que trabajan de manera paralela y con un tiempo de servicio de 11 clientes por hora(μ\muμ.) que sigue una distribución exponencial.

Se desea analizar el desempeño del sistema de espera y responder las siguientes preguntas:

1. Tiempo de espera promedio en la fila antes de ser atendido.

2. Tiempo total promedio en el sistema (incluyendo servicio).

3. Número promedio de clientes en el sistema en cualquier instante.

4. Probabilidad de que un cliente tenga que esperar (es decir, todos los servidores están ocupados).

5. Nivel de utilización del sistema (ratio entre la tasa de llegada y la capacidad total de servicio).

In [135]:
from math import exp
from math import factorial

In [136]:
#UtilizacionPromedio
def p(tasaLlegada, tasaServicio, servidores):
    return (float(tasaLlegada/(tasaServicio*servidores)))

In [137]:
#p0
def pZero(tasaLlegada, tasaServicio, servidores):
    calc_parte1 = 0
    for x in range(servidores):
        calc_parte1 += ((tasaLlegada/tasaServicio)**x)/factorial(x)
    seccion1 = ((tasaLlegada/tasaServicio)**servidores/factorial(servidores))
    seccion2 = 1/(1-p(tasaLlegada, tasaServicio, servidores))
    result_seccion2 = seccion1 * seccion2
    return 1/ (calc_parte1 + result_seccion2)

In [138]:
#NUMERO ESPERADO DE CLIENTES EN COLA (LQ)
def lq(tasaServicio, tasaLlegada, servidores):
    num = pZero(tasaLlegada, tasaServicio, servidores) * ((tasaLlegada/tasaServicio)**servidores) * p(tasaLlegada, tasaServicio, servidores)
    den = factorial(servidores) * ((1-p(tasaLlegada, tasaServicio, servidores))**2)

    return num/den

In [139]:
def l(tasaServicio, tasaLlegada, servidores):
    return lq(tasaServicio, tasaLlegada, servidores) + (tasaLlegada/tasaServicio)

In [140]:
#TIEMPO PROMEDIO EN COLA
def wq(tasaServicio, tasaLlegada, servidores):
    return lq(tasaServicio, tasaLlegada, servidores) / tasaLlegada  

In [141]:
def w(tasaServicio, tasaLlegada, servidores):
    return wq(tasaServicio, tasaLlegada, servidores) + (1/tasaServicio)

In [142]:
def Pw(tasaServicio, tasaLlegada, servidores):
    mult1 = 1/factorial(servidores)
    mult2 = (tasaLlegada/tasaServicio)**servidores
    mutl3 = (servidores*tasaServicio)/(servidores*tasaServicio - tasaLlegada)
    mult4 = pZero(tasaLlegada, tasaServicio, servidores)
    return mult1 * mult2 * mutl3 * mult4


In [143]:
tasaLlegada = int(input("Ingrese la tasa de llegadas por hora: "))
tasaServicio = int(input("Ingrese el ritmo de servicio por hora: "))
servidores = int(input("Ingrese el numero de servidores: "))

In [144]:
print("Tiempo de espera promedio en la fila antes de ser atendido.", wq(tasaServicio, tasaLlegada, servidores))

Tiempo de espera promedio en la fila antes de ser atendido. 0.0016303136443241524


In [145]:
print("Tiempo total promedio en el sistema (incluyendo servicio).", w(tasaServicio, tasaLlegada, servidores))

Tiempo total promedio en el sistema (incluyendo servicio). 0.09253940455341507


In [146]:
print("Número promedio de clientes en el sistema en cualquier instante.", l(tasaServicio, tasaLlegada, servidores))

Número promedio de clientes en el sistema en cualquier instante. 0.7403152364273206


In [147]:
print("Probabilidad de que un cliente tenga que esperar (es decir, todos los servidores están ocupados).", Pw(tasaServicio, tasaLlegada, servidores))

Probabilidad de que un cliente tenga que esperar (es decir, todos los servidores están ocupados). 0.04075784110810381


In [148]:
print("5. Nivel de utilización del sistema (ratio entre la tasa de llegada y la capacidad total de servicio).", p(tasaLlegada, tasaServicio, servidores))

5. Nivel de utilización del sistema (ratio entre la tasa de llegada y la capacidad total de servicio). 0.24242424242424243
